import React, { useState, useEffect } from 'react';
import { supabase } from '../config/supabase';
import { Zap, TrendingUp, Calendar, ArrowUpRight, Download, CreditCard, Loader2, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { generateElectricityBillPDF } from '../utils/pdfUtils';
import { loadRazorpay, createRazorpayOrder, verifyPaymentOnBackend } from '../utils/razorpay';
import { toast } from 'react-hot-toast';

const ElectricityBill = ({ booking, userData }) => {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [paying, setPaying] = useState(false);
  const [pg, setPg] = useState(null);

  useEffect(() => {
    if (booking?.room_id) {
      fetchBills();
      fetchPGInfo();
    }
  }, [booking]);

  const fetchPGInfo = async () => {
    const { data } = await supabase.from('pgs').select('*').eq('id', booking.pg_id).single();
    if (data) setPg(data);
  };

  const handlePayment = async (bill) => {
    if (bill.is_paid) return toast.success('Bill is already paid!');
    setPaying(true);
    
    try {
      // 1. Load Razorpay
      const res = await loadRazorpay();
      if (!res) throw new Error('Razorpay SDK failed to load');

      // 2. Create Order
      const orderData = await createRazorpayOrder(bill.amount);
      if (!orderData) throw new Error('Failed to create order');

      // 3. Open Razorpay Checkout
      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID,
        amount: orderData.amount,
        currency: "INR",
        name: "Apna Rooms",
        description: `Electricity Bill - ${bill.billing_month}`,
        order_id: orderData.id,
        handler: async (response) => {
          // 4. Verify Payment
          const verifyRes = await verifyPaymentOnBackend({
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            booking_details: {
              booking_id: booking.id,
              bill_id: bill.id,
              amount: bill.amount,
              type: 'electricity'
            }
          });

          if (verifyRes.status === 'success') {
            toast.success('Payment successful!');
            fetchBills(); // Refresh data
          } else {
            toast.error('Payment verification failed');
          }
        },
        prefill: {
          name: userData?.full_name,
          email: userData?.email
        },
        theme: { color: "#2196F3" }
      };

      const paymentObject = new window.Razorpay(options);
      paymentObject.open();
    } catch (error) {
      console.error('Payment error:', error);
      toast.error(error.message || 'Payment failed');
    } finally {
      setPaying(false);
    }
  };

  const fetchBills = async () => {
    try {
      const { data, error } = await supabase
        .from('electricity_bills')
        .select(`*, rooms (room_number)`)
        .eq('room_id', booking.room_id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      if (data) setBills(data);
    } catch (error) {
      console.error('Error fetching bills:', error);
    } finally {
      setLoading(false);
    }
  };

  const currentBill = bills[0];

  if (loading) return <div className="p-8 text-center text-gray-500">Loading bill data...</div>;

  if (!currentBill && bills.length === 0) {
    return (
      <div className="space-y-8">
        <div>
          <h2 className="text-3xl font-bold mb-2">Electricity Bill</h2>
          <p className="text-gray-500">No electricity bills generated for this room yet.</p>
        </div>
        <div className="bg-blue-50 p-8 rounded-3xl border border-blue-100 text-center">
          <Zap className="w-12 h-12 text-accent mx-auto mb-4 opacity-20" />
          <p className="text-blue-900 font-medium">Your monthly electricity consumption will appear here once generated by the admin.</p>
        </div>
      </div>
    );
  }

  // Use the real data or fallback to the most recent bill
  const displayBill = currentBill || { units: 0, rate: 0, amount: 0, billing_month: 'N/A' };

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-3xl font-bold mb-2">Electricity Bill</h2>
        <p className="text-gray-500">Track your monthly consumption and payments for Room {booking?.rooms?.room_number}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <Zap className="w-6 h-6 text-accent" />
            </div>
            <span className="text-xs font-bold text-accent bg-blue-100 px-2 py-1 rounded">{displayBill.billing_month}</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Units Consumed</h3>
          <p className="text-3xl font-bold text-primary">{displayBill.units} <span className="text-lg font-normal text-gray-400">kWh</span></p>
        </div>

        <div className="bg-yellow-50 p-6 rounded-2xl border border-yellow-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <TrendingUp className="w-6 h-6 text-yellow-600" />
            </div>
            <span className="text-xs font-bold text-yellow-600 bg-yellow-100 px-2 py-1 rounded">Rate</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Rate per Unit</h3>
          <p className="text-3xl font-bold text-primary">₹{displayBill.rate}</p>
        </div>

        <div className="bg-green-50 p-6 rounded-2xl border border-green-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <Calendar className="w-6 h-6 text-green-600" />
            </div>
            <span className="text-xs font-bold text-green-600 bg-green-100 px-2 py-1 rounded">{displayBill.is_paid ? 'Paid' : 'Unpaid'}</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Payable Amount</h3>
          <p className="text-3xl font-bold text-primary">₹{displayBill.amount}</p>
        </div>
      </div>

      {/* Payment & Download Controls */}
      {!displayBill.is_paid ? (
        <div className="bg-white p-8 rounded-3xl border-2 border-dashed border-accent/20 flex flex-col md:flex-row items-center justify-between space-y-4 md:space-y-0">
          <div className="flex items-center space-x-4">
            <div className="p-4 bg-blue-50 rounded-2xl">
              <CreditCard className="w-8 h-8 text-accent" />
            </div>
            <div>
              <h4 className="text-xl font-bold">Pending Payment</h4>
              <p className="text-gray-500 text-sm">Please pay your bill for {displayBill.billing_month}</p>
            </div>
          </div>
          <div className="flex space-x-3 w-full md:w-auto">
            <button 
              onClick={() => generateElectricityBillPDF(displayBill, userData, pg)}
              className="flex-1 md:flex-none px-6 py-4 bg-gray-50 text-accent font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-gray-100 transition-all"
            >
              <Download className="w-5 h-5" />
              <span>Download Bill</span>
            </button>
            <button 
              onClick={() => handlePayment(displayBill)}
              disabled={paying}
              className="flex-1 md:flex-none px-8 py-4 bg-accent text-white font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-blue-600 transition-all shadow-lg shadow-blue-100 disabled:opacity-50"
            >
              {paying ? <Loader2 className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5" />}
              <span>Pay Now</span>
            </button>
          </div>
        </div>
      ) : (
        <div className="bg-green-50 p-8 rounded-3xl border border-green-100 flex flex-col md:flex-row items-center justify-between space-y-4 md:space-y-0">
          <div className="flex items-center space-x-4">
            <div className="p-4 bg-white rounded-2xl shadow-sm">
              <CheckCircle2 className="w-8 h-8 text-green-500" />
            </div>
            <div>
              <h4 className="text-xl font-bold text-green-900">Bill Paid Successfully</h4>
              <p className="text-green-700/70 text-sm">Thank you for your payment on {displayBill.billing_month}</p>
            </div>
          </div>
          <button 
            onClick={() => generateElectricityBillPDF(displayBill, userData, pg)}
            className="w-full md:w-auto px-8 py-4 bg-white text-green-600 font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-green-100 transition-all border border-green-200"
          >
            <Download className="w-5 h-5" />
            <span>Download Receipt</span>
          </button>
        </div>
      )}

      {/* Consumption Bar Chart - Using Real History */}
      <div className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm">
        <h3 className="text-xl font-bold mb-6">Consumption History (Last {bills.length} Months)</h3>
        <div className="flex items-end justify-between h-64 space-x-2 md:space-x-4">
          {[...bills].reverse().slice(-6).map((item, idx) => (
            <div key={idx} className="flex-1 flex flex-col items-center group">
              <motion.div 
                initial={{ height: 0 }}
                animate={{ height: `${(Number(item.units) / (Math.max(...bills.map(b => Number(b.units))) || 200)) * 100}%` }}
                className="w-full bg-blue-100 rounded-t-lg group-hover:bg-accent transition-colors relative"
              >
                <span className="absolute -top-8 left-1/2 transform -translate-x-1/2 text-xs font-bold text-gray-500 opacity-0 group-hover:opacity-100 transition-opacity">
                  {item.units}
                </span>
              </motion.div>
              <span className="mt-4 text-[10px] font-bold text-gray-400 uppercase tracking-wider">{item.billing_month.split(' ')[0]}</span>
            </div>
          ))}
          {bills.length === 0 && <div className="w-full text-center text-gray-300 italic">No consumption data recorded yet</div>}
        </div>
      </div>
    </div>
  );
};

export default ElectricityBill;
