import React, { useState, useEffect } from 'react';
import { supabase } from '../config/supabase';
import { Zap, TrendingUp, Calendar, ArrowUpRight, Download, CreditCard, Loader2, CheckCircle2, BarChart3 } from 'lucide-react';
import { motion } from 'framer-motion';
import { generateElectricityBillPDF } from '../utils/pdfUtils';
import { loadRazorpay, createRazorpayOrder, verifyPaymentOnBackend } from '../utils/razorpay';
import { toast } from 'react-hot-toast';

const ElectricityBill = ({ booking, userData }) => {
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [paying, setPaying] = useState(false);
  const [pg, setPg] = useState(null);

  useEffect(() => {
    if (booking?.room_id) {
      fetchBills();
      fetchPGInfo();
    }
  }, [booking]);

  const fetchPGInfo = async () => {
    const { data } = await supabase.from('pgs').select('*').eq('id', booking.pg_id).single();
    if (data) setPg(data);
  };

  const handlePayment = async (bill) => {
    if (bill.is_paid) return toast.success('Bill is already paid!');
    setPaying(true);
    
    try {
      // 1. Load Razorpay
      const res = await loadRazorpay();
      if (!res) throw new Error('Razorpay SDK failed to load');

      // 2. Create Order
      const orderData = await createRazorpayOrder(bill.amount);
      if (!orderData) throw new Error('Failed to create order');

      // 3. Open Razorpay Checkout
      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID,
        amount: orderData.amount,
        currency: "INR",
        name: "Apna Rooms",
        description: `Electricity Bill - ${bill.billing_month}`,
        order_id: orderData.id,
        handler: async (response) => {
          // 4. Verify Payment
          const verifyRes = await verifyPaymentOnBackend({
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            booking_details: {
              booking_id: booking.id,
              bill_id: bill.id,
              amount: bill.amount,
              type: 'electricity'
            }
          });

          if (verifyRes.status === 'success') {
            toast.success('Payment successful!');
            fetchBills(); // Refresh data
          } else {
            toast.error('Payment verification failed');
          }
        },
        prefill: {
          name: userData?.fullName || userData?.full_name || '',
          email: userData?.email
        },
        theme: { color: "#2196F3" }
      };

      const paymentObject = new window.Razorpay(options);
      paymentObject.open();
    } catch (error) {
      console.error('Payment error:', error);
      toast.error(error.message || 'Payment failed');
    } finally {
      setPaying(false);
    }
  };

  const fetchBills = async () => {
    try {
      const { data, error } = await supabase
        .from('electricity_bills')
        .select(`*, rooms (room_number)`)
        .eq('room_id', booking.room_id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      if (data) setBills(data);
    } catch (error) {
      console.error('Error fetching bills:', error);
    } finally {
      setLoading(false);
    }
  };

  const parseBillingMonth = (billingMonth) => {
    const parsedDate = new Date(`1 ${billingMonth}`);
    return Number.isNaN(parsedDate.getTime()) ? 0 : parsedDate.getTime();
  };

  const sortedBills = [...bills].sort((a, b) => parseBillingMonth(a.billing_month) - parseBillingMonth(b.billing_month));
  const currentBill = sortedBills[sortedBills.length - 1];
  const lastSixMonths = sortedBills.slice(-6);
  const maxUnits = Math.max(...lastSixMonths.map(bill => Number(bill.units) || 0), 100);
  const avgUnits = lastSixMonths.length > 0 ? Math.round(lastSixMonths.reduce((sum, bill) => sum + Number(bill.units), 0) / lastSixMonths.length) : 0;
  const totalCost = lastSixMonths.reduce((sum, bill) => sum + Number(bill.amount), 0);

  if (loading) return <div className="p-8 text-center text-gray-500">Loading bill data...</div>;

  if (!currentBill && bills.length === 0) {
    return (
      <div className="space-y-8">
        <div>
          <h2 className="text-3xl font-bold mb-2">Electricity Bill</h2>
          <p className="text-gray-500">No electricity bills generated for this room yet.</p>
        </div>
        <div className="bg-blue-50 p-8 rounded-3xl border border-blue-100 text-center">
          <Zap className="w-12 h-12 text-accent mx-auto mb-4 opacity-20" />
          <p className="text-blue-900 font-medium">Your monthly electricity consumption will appear here once generated by the admin.</p>
        </div>
      </div>
    );
  }

  // Use the real data or fallback to the most recent bill
  const displayBill = currentBill || { units: 0, rate: 0, amount: 0, billing_month: 'N/A' };

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-3xl font-bold mb-2">Electricity Bill</h2>
        <p className="text-gray-500">Track your monthly consumption and payments for Room {booking?.rooms?.room_number}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <Zap className="w-6 h-6 text-accent" />
            </div>
            <span className="text-xs font-bold text-accent bg-blue-100 px-2 py-1 rounded">{displayBill.billing_month}</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Units Consumed</h3>
          <p className="text-3xl font-bold text-primary">{displayBill.units} <span className="text-lg font-normal text-gray-400">kWh</span></p>
        </div>

        <div className="bg-yellow-50 p-6 rounded-2xl border border-yellow-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <TrendingUp className="w-6 h-6 text-yellow-600" />
            </div>
            <span className="text-xs font-bold text-yellow-600 bg-yellow-100 px-2 py-1 rounded">Rate</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Rate per Unit</h3>
          <p className="text-3xl font-bold text-primary">₹{displayBill.rate}</p>
        </div>

        <div className="bg-green-50 p-6 rounded-2xl border border-green-100">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-white rounded-xl shadow-sm">
              <Calendar className="w-6 h-6 text-green-600" />
            </div>
            <span className="text-xs font-bold text-green-600 bg-green-100 px-2 py-1 rounded">{displayBill.is_paid ? 'Paid' : 'Unpaid'}</span>
          </div>
          <h3 className="text-gray-500 text-sm font-medium">Payable Amount</h3>
          <p className="text-3xl font-bold text-primary">₹{displayBill.amount}</p>
        </div>
      </div>

      {/* Payment & Download Controls */}
      {!displayBill.is_paid ? (
        <div className="bg-white p-8 rounded-3xl border-2 border-dashed border-accent/20 flex flex-col md:flex-row items-center justify-between space-y-4 md:space-y-0">
          <div className="flex items-center space-x-4">
            <div className="p-4 bg-blue-50 rounded-2xl">
              <CreditCard className="w-8 h-8 text-accent" />
            </div>
            <div>
              <h4 className="text-xl font-bold">Pending Payment</h4>
              <p className="text-gray-500 text-sm">Please pay your bill for {displayBill.billing_month}</p>
            </div>
          </div>
          <div className="flex flex-col md:flex-row space-y-3 md:space-y-0 space-x-0 md:space-x-3 w-full md:w-auto">
            <button 
              onClick={() => generateElectricityBillPDF(displayBill, userData, pg)}
              className="flex-1 md:flex-none px-6 py-4 bg-gray-50 text-accent font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-gray-100 transition-all text-sm"
            >
              <Download className="w-4 h-4" />
              <span>Download Bill</span>
            </button>
            <button 
              onClick={async () => {
                if (displayBill.is_paid) return toast.success('Bill is already paid!');
                toast.success('Please pay the admin offline. Admin will mark it as paid.');
              }}
              className="flex-1 md:flex-none px-6 py-4 bg-white text-gray-700 border-2 border-gray-200 font-bold rounded-xl flex items-center justify-center space-x-2 hover:border-gray-800 transition-all text-sm"
            >
              <span>Pay Offline</span>
            </button>
            <button 
              onClick={() => handlePayment(displayBill)}
              disabled={paying}
              className="flex-1 md:flex-none px-8 py-4 bg-accent text-white font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-blue-600 transition-all shadow-lg shadow-blue-100 disabled:opacity-50 text-sm"
            >
              {paying ? <Loader2 className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5" />}
              <span>Pay Now</span>
            </button>
          </div>
        </div>
      ) : (
        <div className="bg-green-50 p-8 rounded-3xl border border-green-100 flex flex-col md:flex-row items-center justify-between space-y-4 md:space-y-0">
          <div className="flex items-center space-x-4">
            <div className="p-4 bg-white rounded-2xl shadow-sm">
              <CheckCircle2 className="w-8 h-8 text-green-500" />
            </div>
            <div>
              <h4 className="text-xl font-bold text-green-900">Bill Paid Successfully</h4>
              <p className="text-green-700/70 text-sm">Thank you for your payment on {displayBill.billing_month}</p>
            </div>
          </div>
          <button 
            onClick={() => generateElectricityBillPDF(displayBill, userData, pg)}
            className="w-full md:w-auto px-8 py-4 bg-white text-green-600 font-bold rounded-xl flex items-center justify-center space-x-2 hover:bg-green-100 transition-all border border-green-200"
          >
            <Download className="w-5 h-5" />
            <span>Download Receipt</span>
          </button>
        </div>
      )}

      {/* Consumption Bar Chart - Using Real History */}
      <div className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-2xl font-bold flex items-center">
              <BarChart3 className="w-6 h-6 text-accent mr-3" />
              Consumption History
            </h3>
            <p className="text-gray-500 text-sm mt-2">{lastSixMonths.length >= 6 ? 'Last 6 months' : `Last ${lastSixMonths.length} months`} - {avgUnits} kWh average</p>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-500">Total Cost</div>
            <div className="text-3xl font-black text-accent">₹{totalCost}</div>
          </div>
        </div>

        {lastSixMonths.length > 0 ? (
          <div>
            {/* Bar Chart */}
            <div className="mb-8">
              <div className="flex justify-between h-80 space-x-2 md:space-x-3 gap-2 p-4 bg-gradient-to-b from-accent/5 to-transparent rounded-2xl">
                {lastSixMonths.map((item, idx) => {
                  const heightPercent = (Number(item.units) / maxUnits) * 100;
                  const amount = Number(item.amount);
                  
                  return (
                    <motion.div 
                      key={idx} 
                      className="flex-1 h-full flex flex-col items-center group"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: idx * 0.1 }}
                    >
                      {/* Bar Container (takes remaining space) */}
                      <div className="flex-1 w-full flex items-end justify-center relative">
                        {/* Bar */}
                        <motion.div 
                          initial={{ height: 0 }}
                          animate={{ height: `${heightPercent}%` }}
                          transition={{ delay: idx * 0.1 + 0.3, duration: 0.6 }}
                          className="w-full bg-gradient-to-t from-accent to-blue-400 rounded-t-lg group-hover:from-blue-600 group-hover:to-blue-500 transition-all relative shadow-lg hover:shadow-xl"
                        >
                          {/* Tooltip on hover */}
                          <div className="absolute -top-20 left-1/2 transform -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity bg-gray-900 text-white px-3 py-2 rounded-lg text-xs font-bold whitespace-nowrap shadow-xl z-20">
                            <div>{item.units} kWh</div>
                            <div className="text-green-300">₹{amount}</div>
                            <div className="text-gray-300 text-[10px]">{item.billing_month}</div>
                          </div>
                        </motion.div>
                      </div>

                      {/* Month Label */}
                      <div className="mt-4 text-center">
                        <span className="text-xs font-bold text-gray-600 uppercase tracking-wide block">
                          {item.billing_month.split(' ')[0].substring(0, 3)}
                        </span>
                        <span className="text-[10px] font-medium text-gray-400">
                          {item.billing_month.split(' ')[1]}
                        </span>
                      </div>

                      {/* Units Display */}
                      <div className="mt-1 text-[11px] font-bold text-accent text-center">
                        {item.units} kWh
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </div>

            {/* Stats Row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-6 border-t border-gray-100">
              <div className="bg-blue-50 p-4 rounded-2xl border border-blue-100">
                <div className="text-xs font-bold text-gray-500 uppercase tracking-wider">Max Consumption</div>
                <div className="text-2xl font-black text-accent mt-2">{Math.max(...lastSixMonths.map(b => Number(b.units)), 0)} kWh</div>
              </div>
              <div className="bg-green-50 p-4 rounded-2xl border border-green-100">
                <div className="text-xs font-bold text-gray-500 uppercase tracking-wider">Average</div>
                <div className="text-2xl font-black text-green-600 mt-2">{avgUnits} kWh</div>
              </div>
              <div className="bg-yellow-50 p-4 rounded-2xl border border-yellow-100">
                <div className="text-xs font-bold text-gray-500 uppercase tracking-wider">Total Units</div>
                <div className="text-2xl font-black text-yellow-600 mt-2">{lastSixMonths.reduce((sum, bill) => sum + Number(bill.units), 0)} kWh</div>
              </div>
              <div className="bg-purple-50 p-4 rounded-2xl border border-purple-100">
                <div className="text-xs font-bold text-gray-500 uppercase tracking-wider">Avg Rate</div>
                <div className="text-2xl font-black text-purple-600 mt-2">₹{lastSixMonths.length > 0 ? Math.round(totalCost / lastSixMonths.reduce((sum, bill) => sum + Number(bill.units), 1)) : 0}/kWh</div>
              </div>
            </div>

            {/* Detailed Table */}
            <div className="mt-8 rounded-2xl border border-gray-200 overflow-hidden">
              <table className="w-full text-sm">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-4 text-left font-bold text-gray-700">Month</th>
                    <th className="px-6 py-4 text-right font-bold text-gray-700">Units (kWh)</th>
                    <th className="px-6 py-4 text-right font-bold text-gray-700">Rate/Unit</th>
                    <th className="px-6 py-4 text-right font-bold text-gray-700">Amount</th>
                    <th className="px-6 py-4 text-center font-bold text-gray-700">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {lastSixMonths.map((bill, idx) => (
                    <tr key={idx} className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'} >
                      <td className="px-6 py-4 font-medium text-gray-800">{bill.billing_month}</td>
                      <td className="px-6 py-4 text-right font-bold text-accent">{bill.units}</td>
                      <td className="px-6 py-4 text-right text-gray-600">₹{bill.rate}</td>
                      <td className="px-6 py-4 text-right font-bold text-gray-900">₹{bill.amount}</td>
                      <td className="px-6 py-4 text-center">
                        <span className={`px-3 py-1 rounded-full text-xs font-bold ${bill.is_paid ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>
                          {bill.is_paid ? 'Paid' : 'Pending'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ) : (
          <div className="text-center py-16 text-gray-400">
            <BarChart3 className="w-12 h-12 mx-auto mb-4 opacity-20" />
            <p className="font-medium italic">No consumption data recorded yet for this room</p>
            <p className="text-sm mt-2">Bills will be generated monthly by the admin</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ElectricityBill;

